[build]
  command = "node build.js"
  publish = "." # Publica a raiz do projeto, onde está o mapa.html e pontos.json

[[redirects]]
from = "/admin/*"
to = "/admin/index.html"
status = 200

[[redirects]]
  from = "/*"
  to = "/mapa.html"
  status = 200
