# netlify.toml
[build]
  command = "" # Seu comando de build, se houver
  publish = "public" # O diretório de arquivos estáticos a ser servido

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
