# Remova a seção [build] se for usar a GitHub Action para gerar o pontos.json
# A Netlify só precisa publicar os arquivos que já estão no repositório.
[build]
  publish = "." # Apenas informa qual pasta publicar

# Remova a seção de redirects, ela não é necessária e está causando o erro.
# A Netlify já entende que /admin/ deve servir /admin/index.html por padrão.
