# netlify.toml
[build]
  command = "npm run build:points" # Ou qualquer outro comando de build que você tenha
  publish = "." # Ou o diretório que você publica, ex: "public", "dist"

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200
  force = true
