backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "pt"

collections:
  - name: "pontos"
    label: "Todos os Pontos do Mapa"
    files:
      - label: "Pontos"
        name: "pontos"
        file: "dados/pontos.json"
        format: "json"
        fields:
          - label: "Atualizado em"
            name: "atualizado_em"
            widget: "datetime"
            default: ""
          - label: "Lista de Pontos"
            name: "pontos"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text" }
              - { label: "Latitude", name: "latitude", widget: "string" }
              - { label: "Longitude", name: "longitude", widget: "string" }
              - { label: "Imagem", name: "imagem", widget: "image" }
              - { label: "Link", name: "link", widget: "string" }
