backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    folder: "data/pontos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Latitude", name: "lat", widget: "string" }
      - { label: "Longitude", name: "lng", widget: "string" }
      - { label: "Imagem", name: "image", widget: "image" }
