backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    label_singular: "Ponto"
    delete: false
    editor:
      preview: false
    files:
      - file: "pontos.json"
        label: "Todos os Pontos"
        name: "todos_pontos"
        fields:
          - label: "Última Atualização"
            name: "atualizado_em"
            widget: "datetime"
            default: ""
          - label: "Lista de Pontos"
            name: "pontos"
            widget: "list"
            summary: "{{fields.nome}}"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text", required: false }
              - { label: "Latitude", name: "latitude", widget: "number", value_type: "float", step: 0.0000001 }
              - { label: "Longitude", name: "longitude", widget: "number", value_type: "float", step: 0.0000001 }
              - { label: "Imagem", name: "imagem", widget: "image", required: false }
              - { label: "Link (ex: WhatsApp)", name: "link", widget: "string", required: false }
