backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "pt"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    format: "json"
    extension: "json"
    editor:
      preview: false
    files:
      - label: "Todos os Pontos"
        name: "pontos"
        file: "pontos.json"
        fields:
          - label: "Data da última atualização"
            name: "atualizado_em"
            widget: "datetime"
            default: ""
          - label: "Lista de Pontos"
            name: "pontos"
            widget: "list"
            fields:
              - { label: "Nome", name: "nome", widget: "string" }
              - { label: "Descrição", name: "descricao", widget: "text", required: false }
              - { label: "Latitude", name: "latitude", widget: "number", value_type: "float" }
              - { label: "Longitude", name: "longitude", widget: "number", value_type: "float" }
              - { label: "Imagem", name: "imagem", widget: "image", required: false }
              - { label: "Link", name: "link", widget: "string", required: false }
