backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "pt"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    folder: "dados/pontos"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nome", name: "nome", widget: "string", required: true }
      - { label: "Descrição", name: "descricao", widget: "text", required: false }
      - { label: "Latitude", name: "latitude", widget: "string", required: true }
      - { label: "Longitude", name: "longitude", widget: "string", required: true }
      - { label: "Imagem", name: "imagem", widget: "image", required: false }
      - { label: "Link do WhatsApp", name: "link", widget: "string", required: false, hint: "Cole aqui o link completo do WhatsApp" }
