backend:
  name: github
  repo: sobrejeri/mapa-wix
  branch: main
  use_graphql: true

media_folder: "uploads"
public_folder: "/uploads"

locale: "pt"
site_url: "https://sobrejeri.github.io/mapa-wix"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    folder: "dados"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nome", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
      - { label: "Latitude", name: "lat", widget: "string" }
      - { label: "Longitude", name: "lng", widget: "string" }
