backend:
  name: test-repo
  branch: main
  local_backend: true

media_folder: "static/uploads"       # Onde as imagens vão no repositório
public_folder: "/static/uploads"     # Caminho acessível no site

collections:
  - name: "pontos"
    label: "Pontos no Mapa"
    folder: "data/pontos"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "description", widget: "text" }
      - { label: "Imagem", name: "image", widget: "image" }
      - { label: "Latitude", name: "latitude", widget: "string" }
      - { label: "Longitude", name: "longitude", widget: "string" }
backend:
  name: test-repo
  branch: main
  local_backend: true
