backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

locale: "pt"

collections:
  - name: "pontos"
    label: "Pontos do Mapa"
    folder: "dados/pontos"
    create: true
    slug: "{{slug}}"
    format: "json"
    extension: "json"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Latitude", name: "latitude", widget: "string" }
      - { label: "Longitude", name: "longitude", widget: "string" }
      - { label: "Imagem", name: "imagem", widget: "image" }
      - { label: "Link", name: "link", widget: "string" }
