backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "pontos"
    label: "Imóveis no Mapa"
    folder: "dados/pontos"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"
    fields:
      - { label: "Nome", name: "nome", widget: "string" }
      - { label: "Descrição", name: "descricao", widget: "text" }
      - { label: "Preço", name: "preco", widget: "string" }
      - { label: "Tipo", name: "tipo", widget: "select", options: ["Terreno", "Casa", "Comercial", "Pousada", "Outros"] }
      - { label: "Status", name: "status", widget: "select", options: ["Disponível", "Vendido", "Reservado"] }
      - { label: "Latitude", name: "latitude", widget: "number", value_type: "float", step: 0.00001 }
      - { label: "Longitude", name: "longitude", widget: "number", value_type: "float", step: 0.00001 }
      - { label: "Imagem de capa", name: "imagem_capa", widget: "image" }
      - { label: "Galeria de imagens", name: "galeria", widget: "list", field: { label: "Imagem", name: "imagem", widget: "image" } }
      - { label: "Link do vídeo", name: "video", widget: "string", required: false }
      - { label: "WhatsApp", name: "whatsapp", widget: "string" }
