name: Atualizar pontos.json

on:
  push:
    paths:
      - 'dados/pontos/*.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Juntar arquivos JSON da pasta dados/pontos
        run: |
          mkdir -p dados/pontos
          echo '{ "atualizado_em": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'", "pontos": [' > pontos.json
          find dados/pontos -name "*.json" -exec cat {} \; | jq -s '.[]' | jq -s 'add | .[]' >> pontos.json
          echo ']}' >> pontos.json

      - name: Commit e push do pontos.json
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "github-bot"
          git add pontos.json
          git commit -m "Atualizar pontos.json automaticamente" || echo "Sem alterações para commitar"
          git push
